apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
// Apply the Crashlytics Gradle plugin
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'

android {
    configurations {
//        all*.exclude group: 'com.squareup.okhttp', module: 'okhttp'
//        all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
  /*  signingConfigs {
        config {
            keyAlias 'lspro'
            keyPassword '123456'
            storeFile file('lspro.jks')
            storePassword '123456'
        }
    } */
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    }
    compileSdkVersion 34
    buildToolsVersion '33.0.0'
    defaultConfig {
        applicationId "com.multixpro.store"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    flavorDimensions "default"

    buildFeatures {
        dataBinding = true
    }

    dexOptions {
        jumboMode true
    }
    productFlavors {
        dev {
            // dev utilizes minSDKVersion = 21 to allow the Android gradle plugin
            // to pre-dex each module and produce an APK that can be tested on
            // Android Lollipop without time consuming dex merging processes.
            minSdkVersion 21
        }
        prod {
            // The actual minSdkVersion for the application.
            minSdkVersion 21
        }
    }
    buildTypes {
        release {
            debuggable false
            buildConfigField "String", "USER_TYPE", "\"Company\""
            buildConfigField "String", "USER_ID_KEY", "\"iCompanyId\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
          //  signingConfig signingConfigs.config
        }
        debug {
            debuggable true
            buildConfigField "String", "USER_TYPE", "\"Company\""
            buildConfigField "String", "USER_ID_KEY", "\"iCompanyId\""
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            minifyEnabled false
          //  signingConfig signingConfigs.config
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }

    packagingOptions {

        exclude 'META-INF/NOTICE' // will not include NOTICE file
        exclude 'META-INF/LICENSE' // will not include LICENSE file
        // as noted by @Vishnuvathsan you may also need to include
        // variations on the file name. It depends on your dependencies.
        // Some other common variations on notice and license file names
        exclude 'META-INF/notice'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    // TODO: 12-12-2021 / Viral | AUDIO_CALLING_METHOD = LOCAL
    implementation fileTree(include: ['*.jar', 'SysBaseLib.aar', 'sinch_lib.aar', 'ShadowLayout.aar', 'Skeleton.aar', 'AppDatePicker.aar'], dir: 'libs')

    //implementation 'com.infobip:google-webrtc:1.0.0035529'
    implementation 'org.webrtc:google-webrtc:1.0.32006'

    // TODO: 12-12-2021 / Viral | AUDIO_CALLING_METHOD = SINCH
    //implementation fileTree(include: ['*.jar', 'SysBaseLib.aar', 'sinch_lib_v.aar', 'ShadowLayout.aar', 'Skeleton.aar', 'AppDatePicker.aar'], dir: 'libs')

    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.core:core-splashscreen:1.1.0-alpha01"
    implementation 'androidx.core:core-ktx:1.9.0'
    testImplementation 'junit:junit:4.13.2'

    /* Customize PubNub Library and OKHttp*/
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'com.squareup.okio:okio:2.10.0'
    /* Customize PubNub Library and OKHttp*/

    /* RetroFit related libraries*/
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    /* RetroFit related libraries*/

    /* Android support libraries */
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.browser:browser:1.4.0'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.annotation:annotation:1.5.0'
    //implementation 'androidx.palette:palette:1.0.0'
    //implementation 'androidx.exifinterface:exifinterface:1.0.0'
    /* Android support libraries */

    /* Google services related libraries */
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.google.android.gms:play-services-location:20.0.0'
    implementation 'com.google.android.gms:play-services-maps:18.1.0'
    implementation 'com.google.android.gms:play-services-places:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:20.3.0'
    implementation 'com.google.maps.android:android-maps-utils:2.2.5'
    implementation 'com.google.firebase:firebase-database:20.0.6'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:23.0.8'
    implementation 'com.google.firebase:firebase-auth:21.0.8'

    // Recommended: Add the Firebase SDK for Google Analytics.
    implementation 'com.google.firebase:firebase-analytics:21.1.1'

    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:18.2.13'

    /* Google services related libraries */

    implementation 'org.apache.commons:commons-lang3:3.6'


    //implementation 'com.facebook.android:facebook-login:12.3.0'

    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.kyleduo.switchbutton:library:2.1.0'

    implementation 'com.squareup.picasso:picasso:2.71828'
    // implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'


    implementation 'com.github.bumptech.glide:glide:4.13.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'

    implementation 'com.stripe:stripe-android:8.0.0'

    implementation 'com.neovisionaries:nv-websocket-client:2.12'
    /*implementation('io.github.sac:SocketclusterClientJava:2.0.0') {
        exclude group :'org.json', module: 'json'
    }*/
    implementation 'com.github.livechat:chat-window-android:v2.0.3'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'

    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    implementation 'com.intuit.ssp:ssp-android:1.0.6'
    implementation 'com.github.ViksaaSkool:AutoFitEditText:53238e2d29'
    implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.0.3'
    implementation 'com.skyfishjy.ripplebackground:library:1.0.1'
    //implementation 'com.amitshekhar.android:android-networking:1.0.2'
    implementation 'io.supercharge:shimmerlayout:2.1.0'

    implementation 'androidx.biometric:biometric:1.2.0-alpha05'
    implementation 'com.airbnb.android:lottie:5.2.0'

    implementation 'com.twilio:video-android:7.0.3'
    //implementation 'com.tbuonomo:dotsindicator:4.2'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'

    implementation 'io.github.vejei.viewpagerindicator:viewpagerindicator:1.0.0-alpha.1'

    implementation 'com.google.android.gms:play-services-ads:21.2.0'
    implementation 'com.facebook.android:audience-network-sdk:6.11.0'
}